### PR TITLE
updated speech proto file to enable word offsets

### PR DESCRIPTION
**Pull request by rishavjalan**
From googleapis repository

### CODE REVIEW

**Comment by rishavjalan** [comment]
I signed it! :)

**Comment by rishavjalan** [comment]
@frankyn could you review this and this to the repo as I believe it might help others in testing the word offsets with the sample code on the documentation website.

**Comment by rishavjalan** [comment]
Yeah its fine

**Comment by frankyn** [comment]
@kurtisvg how long does it take for Kokoro to complete tests?

**Comment by kurtisvg** [comment]
@frankyn Since the original author is outside of the GoogleCloudPlatform organization, Kokoro will not queue the job automatically. Instead, you'll need to apply the `kokoro:run` label to this PR after vetting the code.

**Comment by frankyn** [comment]
@kurtisvg Thank you!

**Comment by frankyn** [comment]
@kurtisvg by chance do you know why Kokoro Team automatically removes the label? I see that Kokoro CI started so I'm guessing it removes after it starts the build.

**Comment by kurtisvg** [comment]
@frankyn Yes, it removes it once the job is queued so you know it's running.

**Comment by frankyn** [comment]
Fixed Kokoro CI not running tests in #55. Waiting on build status before merge.

**Comment by frankyn** [comment]
Thanks @rishavjalan, apologies for the delay.

**Comment by lesv** [comment]
Kokoro says this is a problem.


https://kokoro.corp.google.com/job/cloud-devrel/job/java/job/android-docs-samples/job/periodic/131/
Changes include:
        Changelist
https://github.com/GoogleCloudPlatform/android-docs-samples/commit/1027e01b5dd2cd47a52d86a939ef97a1593dc155
by Rishav Jalan: updated speech proto file to enable word offsets (#44)

Not sure why.

**Comment by kurtisvg** [comment]
The periodic test failed for some reason, and this is just the last commit on that branch. It's probably a flaky test somewhere and unrelated to the commit, because it's passed the periodic test dozens of times previously.

**Comment by frankyn** [comment]
@lesv and @kurtisvg, looks like it was only a flake. It had to do with Firebase Testlab failure with legacy EP Android app.

**Pull request merged**
