### PR TITLE
Added continuous and presubmit checks.

### PR DESCRIPTION
**Pull request by kurtisvg**
Testing changes for presubmit checks to this repo.

### CODE REVIEW

**Comment by kurtisvg** [comment]
@lesv, @frankyn - This PR will allow for presubmit testing of the master branch.

**Comment by lesv** [comment]
There is another CL that connects with this.

**Comment by lesv** [comment]
Let me know when everything is working and we can turn CircleCI off for this repo.

**Comment by kurtisvg** [comment]
@lesv @frankyn This is working, you can disable Circle CI. I will catch up with Frank at some-point so we can compare the Circle CI tests to the Kokoro tests and make sure we aren't missing anything.

**Comment by lesv** [comment]
It appears to no longer be here, so I'm presuming Frank did it.

**Comment by frankyn** [comment]
I unassigned it in Circle CI.

**Pull request merged**
